version: '3.8'

services:
  consul-agent:
    image: custom-consul-agent
    container_name: consul-agent
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./consul/consul.hcl.template:/consul/config/consul.hcl.template:ro,z
      - ./consul-data:/consul/data:z
    network_mode: host
    restart: unless-stopped
    entrypoint: ["/entrypoint.sh"]
    environment:
      - MONITORING_HOST=${MONITORING_HOST}
      - CONSUL_NODE_NAME=${CONSUL_NODE_NAME}
      - CONSUL_ADVERTISE=${CONSUL_ADVERTISE}

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - ./node-exporter/entrypoint.sh:/entrypoint.sh
    network_mode: host
    restart: unless-stopped
    entrypoint: ["/entrypoint.sh"]

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:

      - ${PROMTAIL_CONFIG_PATH:-./promtail/config.yml}:/etc/promtail/config.yml:ro,z
      - /var/run/docker.sock:/var/run/docker.sock:ro,Z # Add this line to mount the Docker socket
      - /var/log:/mnt/host/var/log:ro
      - promtail_positions:/promtail/data
    command:
      - "-config.file=/etc/promtail/config.yml"
      # 4. Explicitly tell Promtail where to store its positions file,
      #    pointing to the writable volume.
      - "-positions.file=/promtail/data/positions.yaml"
      - "-config.expand-env=true"
    environment: # Ensure MONITORING_HOST is passed if used in config
      - MONITORING_HOST=${MONITORING_HOST}
    network_mode: host
    restart: unless-stopped
    #entrypoint: ["/entrypoint.sh"]

volumes:
  consul-data:
    driver: local
  promtail_positions: {} 

networks:
  monitoring:
    driver: bridge